#!/bin/bash -e

printvar() {
  local value="$1"
  local key="$2"
  test -z "${value}" && echo "${key}: ${value}"
}

CONF_DIR=~/.jira.d
CONF_BASH=config.sh
CONF_YAML=config.yml.head

cd ${CONF_DIR}
if test -e ${CONF_DIR}/${CONF_BASH}
then
  source ${CONF_DIR}/${CONF_BASH}
  printvar "${JIRA_ENDPOINT}" 'endpoint'
  printvar "${JIRA_USER}" 'user'
  printvar "${JIRA_LOGIN}" 'login'
else
  test -e ${CONF_DIR}/${CONF_YAML} && cat ${CONF_DIR}/${CONF_YAML}
fi

echo 'custom-commands:'
cat ${CONF_DIR}/commands/*
